#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Master CONFIG and its functions."""

from ansible.module_utils.basic import AnsibleModule
import ast

application_name = "LDAP to Subversion Authz Bridge (ansible module)"
application_version = "1.0.0"
application_description = f"""The '{application_name}' is a simple script that will query your
                          directory server for group objects and create a
                          representation of those groups in your Subversion
                          authorization (authz) file."""

CONFIG = {
    'dry_run':              False,
    'debug':                False,
    'ldap' : {
        'url' :             'localhost',
        'bind_dn':          None,
        'bind_pw':          None,
        'search_dn':        None,
        'user_query':       '(&(objectclass=user)'
                            '(!(userAccountControl:1.2.840.113556.1.4.803:=2)))',
        'objid_attribute':  'sAMAccountName',
        'group_traversal':  True,
    },
    'svn': {
        'authz_path':       None,
        'authz_header':     '#\n# Generated by '+application_name +' (ver. '+application_version+')'+
                            '\n#',
        'authz_footer':     '\n',
        'repo_name':        None,
        'repos_root':       '/home/svn',
        'default_perms':    'r',
        'default_everyone_perms': '',
        'default_groupname_pfx': 'svn-',
        'access':  {
            'EVERYONE': None,
        },
    },
}


# groups: 'g1':[], access: '@g1':''...
AUTHZ = {
    'groups': {},
    'access': {}
}

################################################################################
# defs
################################################################################

def load_svn_accesses(access):
    """Loads svn repo access config."""
    if CONFIG['svn']['repo_name'] in access:
        CONFIG['svn']['access'] = access[CONFIG['svn']['repo_name']]
    elif 'default' in access:
        CONFIG['svn']['access'] = access['default']
    else:
        raise Exception(f"[ERROR] please define {CONFIG['svn']['repo_name']} access template or at least default one")


def load(module):
    """Loads CONFIG."""
    CONFIG['dry_run']=module.check_mode
    CONFIG['debug']=ast.literal_eval(module.params['enable_debug'])

    ldap_conf=ast.literal_eval(module.params['ldap'])
    CONFIG['ldap'] = {**CONFIG['ldap'], **ldap_conf}
    CONFIG['svn']['repos_root'] = module.params['repos_root']
    CONFIG['svn']['repo_name'] = module.params['repo_name']
    CONFIG['svn']['authz_path'] = module.params['authz_path']

    load_svn_accesses(ast.literal_eval(module.params['access']))